FROM debian:stable-slim

RUN apt-get update -yq && \
    apt-get install -yq --no-install-recommends ca-certificates tini && \
    rm -rf /var/lib/apt/lists/*

COPY dist/zenpanda /bin/zenpanda
RUN chmod +x /bin/zenpanda

EXPOSE 9222/tcp

ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/zenpanda", "serve", "--host", "0.0.0.0", "--port", "9222", "--log-level", "info", "--cdp-max-connections", "100"]
